==========
Exceptions
==========

All ``pyzeebe`` exceptions inherit from :py:class:`PyZeebeException`

.. autoexception:: pyzeebe.exceptions.PyZeebeException

.. autoexception:: pyzeebe.exceptions.TaskNotFound

.. autoexception:: pyzeebe.exceptions.NoVariableNameGiven

.. autoexception:: pyzeebe.exceptions.NoZeebeAdapter

.. autoexception:: pyzeebe.exceptions.DuplicateTaskType

.. autoexception:: pyzeebe.exceptions.ActivateJobsRequestInvalid

.. autoexception:: pyzeebe.exceptions.JobAlreadyDeactivated

.. autoexception:: pyzeebe.exceptions.JobNotFound

.. autoexception:: pyzeebe.exceptions.MessageAlreadyExists

.. autoexception:: pyzeebe.exceptions.WorkflowNotFound

.. autoexception:: pyzeebe.exceptions.WorkflowInstanceNotFound

.. autoexception:: pyzeebe.exceptions.WorkflowHasNoStartEvent

.. autoexception:: pyzeebe.exceptions.WorkflowInvalid

.. autoexception:: pyzeebe.exceptions.InvalidJSON

.. autoexception:: pyzeebe.exceptions.ZeebeBackPressure

.. autoexception:: pyzeebe.exceptions.ZeebeGatewayUnavailable

.. autoexception:: pyzeebe.exceptions.ZeebeInternalError

.. autoexception:: pyzeebe.exceptions.InvalidOAuthCredentials

.. autoexception:: pyzeebe.exceptions.InvalidCamundaCloudCredentials
